import { color } from './color';
import { typography } from './typography';

export const text = {
  label: {
    medium: {
      color: color.text.primary,
      italic: false,
      fontSize: 14,
      underline: false,
      fontFamily: typography.primaryFont,
      fontWeight: 500,
      letterSpacing: 0,
    },
    small: {
      color: color.text.primary,
      italic: false,
      fontSize: 12,
      underline: false,
      fontFamily: typography.primaryFont,
      fontWeight: 500,
      letterSpacing: 0,
    },
    large: {
      color: color.text.primary,
      italic: false,
      fontSize: 16,
      underline: false,
      fontFamily: typography.primaryFont,
      fontWeight: 500,
      letterSpacing: 0,
    },
  },
  heading: {
    large: {
      color: color.text.primary,
      italic: false,
      fontSize: 32,
      underline: false,
      fontFamily: typography.primaryFont,
      fontWeight: 700,
      letterSpacing: -0.02,
    },
    medium: {
      color: color.text.primary,
      italic: false,
      fontSize: 24,
      underline: false,
      fontFamily: typography.primaryFont,
      fontWeight: 700,
      letterSpacing: -0.01,
    },
    small: {
      color: color.text.primary,
      italic: false,
      fontSize: 18,
      underline: false,
      fontFamily: typography.primaryFont,
      fontWeight: 700,
      letterSpacing: 0,
    },
  },
  hint: {
    color: color.text.tertiary,
    italic: false,
    fontSize: 10,
    underline: false,
    fontFamily: typography.primaryFont,
    fontWeight: 400,
    letterSpacing: 0,
  },
  title: {
    large: {
      color: color.text.primary,
      italic: false,
      fontSize: 24,
      underline: false,
      fontFamily: typography.primaryFont,
      fontWeight: 600,
      letterSpacing: 0,
    },
    medium: {
      color: color.text.primary,
      italic: false,
      fontSize: 18,
      underline: false,
      fontFamily: typography.primaryFont,
      fontWeight: 600,
      letterSpacing: 0,
    },
    small: {
      color: color.text.primary,
      italic: false,
      fontSize: 14,
      underline: false,
      fontFamily: typography.primaryFont,
      fontWeight: 600,
      letterSpacing: 0,
    },
  },
  body: {
    large: {
      color: color.text.primary,
      italic: false,
      fontSize: 16,
      underline: false,
      fontFamily: typography.primaryFont,
      fontWeight: 400,
      letterSpacing: 0,
    },
    medium: {
      color: color.text.primary,
      italic: false,
      fontSize: 14,
      underline: false,
      fontFamily: typography.primaryFont,
      fontWeight: 400,
      letterSpacing: 0,
    },
    small: {
      color: color.text.primary,
      italic: false,
      fontSize: 12,
      underline: false,
      fontFamily: typography.primaryFont,
      fontWeight: 400,
      letterSpacing: 0,
    },
  },
};
